version: "3.9"

services:
  backend:
    depends_on:
      - mssql    
    build:        
      context: .
      dockerfile: ./MoreTech.Api/Dockerfile
      args:
        - CONFIG_FILE_PATH=NuGet.Config
    env_file: more-tech-backend.env
    ports:
      - 5129:80
    restart: always

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=06AA07bb1995cc_
    restart: always