version: "3"

services:
  backend:
    build:        
      context: .
      dockerfile: ./MoreTech.Api/Dockerfile
      args:
        - CONFIG_FILE_PATH=NuGet.Config
    env_file: more-tech-backend.env
    ports:
      - 5129:80
    restart: always

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql_admin
    ports:
      - 1433:1433
    restart: always