version: "3.9"

services:
  backend:
    depends_on:
      - mssql
    networks:
      - my_network
    build:        
      context: .
      dockerfile: ./MoreTech.Api/Dockerfile
      args:
        - CONFIG_FILE_PATH=NuGet.Config
    env_file: more-tech-backend.env
    ports:
      - 5129:80
    restart: always

  mssql:
    container_name: mssql
    hostname: mssql-db
    networks:
      - my_network
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql_admin
    ports:
      - 1433:1433
    restart: always
    
networks:
  my_network:
    driver: bridge